output file:
processed_cleanlabcompute_pyx227.json
function:
compute_pyx
Error Cases:

Pass or Failed: 0

Related Failed Test Cases:
{'../../../../../../local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py::test_pyx_error FAILED', 'FAILED ../../../../../../local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py::test_pyx_error'}

All Test Cases On Generated code:
============================= test session starts ==============================
platform linux -- Python 3.11.10, pytest-8.3.4, pluggy-1.5.0 -- /local/data0/moved_data/publishablew/cleanlab/cleanlab/venv/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase(PosixPath('/home/aliredaq/Desktop/ICSE/src/tester/.hypothesis/examples'))
rootdir: /local/data0/moved_data/publishablew/cleanlab/cleanlab
configfile: pyproject.toml
plugins: hypothesis-6.124.1
collecting ... collected 10 items

../../../../../../local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py::test_latent_py_ps_inv PASSED
../../../../../../local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py::test_latent_inv PASSED
../../../../../../local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py::test_latent_nm PASSED
../../../../../../local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py::test_latent_py PASSED
../../../../../../local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py::test_latent_py_warning PASSED
../../../../../../local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py::test_compute_py_err PASSED
../../../../../../local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py::test_compute_py_marginal_ps PASSED
../../../../../../local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py::test_pyx PASSED
../../../../../../local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py::test_pyx_error FAILED
../../../../../../local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py::test_compute_py_method_marginal_true_labels_class_counts_none_error PASSED

=================================== FAILURES ===================================
________________________________ test_pyx_error ________________________________

    def test_pyx_error():
        pred_probs = np.array([0.1, 0.3, 0.6])
        ps, py, inv = get_latent_py_ps_inv()
        try:
>           pyx = latent_algebra.compute_pyx(pred_probs, nm, inverse_noise_matrix=inv)

/local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py:125: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/local/data0/moved_data/publishablew/cleanlab/cleanlab/cleanlab/internal/latent_algebra.py:214: in compute_pyx
    return compute_pyx(pred_probs, noise_matrix, inverse_noise_matrix)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

pred_probs = array([0.1, 0.3, 0.6])
noise_matrix = array([[1. , 0. , 0.2],
       [0. , 0.7, 0.2],
       [0. , 0.3, 0.6]])
inverse_noise_matrix = array([[5.0000000e-01, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 4.2003982e-06, 5.9999964e-07],
       [5.0000000e-01, 9.9999580e-01, 9.9999940e-01]])

    def compute_pyx(pred_probs, noise_matrix, inverse_noise_matrix):
        """
        Compute pyx := P(true_label=k|x) from pred_probs := P(label=k|x), noise_matrix, and inverse_noise_matrix.
    
        Parameters
        ----------
        pred_probs : np.ndarray
            (N x K) matrix with model-predicted probabilities P(label=k|x).
        noise_matrix : np.ndarray
            (K x K) matrix P(label=k_s|true_label=k_y).
        inverse_noise_matrix : np.ndarray
            (K x K) matrix P(true_label=k_y|label=k_s).
    
        Returns
        -------
        pyx : np.ndarray
            (N x K) matrix of model-predicted probabilities P(true_label=k|x).
        """
        if len(pred_probs.shape) != 2:
>           raise ValueError(f'pred_probs should be a 2D array, but got shape {pred_probs.shape}')
E           ValueError: pred_probs should be a 2D array, but got shape (3,)

/local/data0/moved_data/publishablew/cleanlab/cleanlab/cleanlab/internal/temp.py:27: ValueError

During handling of the above exception, another exception occurred:

    def test_pyx_error():
        pred_probs = np.array([0.1, 0.3, 0.6])
        ps, py, inv = get_latent_py_ps_inv()
        try:
            pyx = latent_algebra.compute_pyx(pred_probs, nm, inverse_noise_matrix=inv)
        except ValueError as e:
>           assert "should be (N, K)" in str(e)
E           AssertionError: assert 'should be (N, K)' in 'pred_probs should be a 2D array, but got shape (3,)'
E            +  where 'pred_probs should be a 2D array, but got shape (3,)' = str(ValueError('pred_probs should be a 2D array, but got shape (3,)'))

/local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py:127: AssertionError
=========================== short test summary info ============================
FAILED ../../../../../../local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py::test_pyx_error
========================= 1 failed, 9 passed in 0.67s ==========================


Final Test Result:
============================= test session starts ==============================
platform linux -- Python 3.11.10, pytest-8.3.4, pluggy-1.5.0 -- /local/data0/moved_data/publishablew/cleanlab/cleanlab/venv/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase(PosixPath('/home/aliredaq/Desktop/ICSE/src/tester/.hypothesis/examples'))
rootdir: /local/data0/moved_data/publishablew/cleanlab/cleanlab
configfile: pyproject.toml
plugins: hypothesis-6.124.1
collecting ... collected 10 items

../../../../../../local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py::test_latent_py_ps_inv PASSED
../../../../../../local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py::test_latent_inv PASSED
../../../../../../local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py::test_latent_nm PASSED
../../../../../../local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py::test_latent_py PASSED
../../../../../../local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py::test_latent_py_warning PASSED
../../../../../../local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py::test_compute_py_err PASSED
../../../../../../local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py::test_compute_py_marginal_ps PASSED
../../../../../../local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py::test_pyx PASSED
../../../../../../local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py::test_pyx_error PASSED
../../../../../../local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py::test_compute_py_method_marginal_true_labels_class_counts_none_error PASSED

============================== 10 passed in 0.58s ==============================


Initial Result:
============================= test session starts ==============================
platform linux -- Python 3.11.10, pytest-8.3.4, pluggy-1.5.0 -- /local/data0/moved_data/publishablew/cleanlab/cleanlab/venv/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase(PosixPath('/home/aliredaq/Desktop/ICSE/src/tester/.hypothesis/examples'))
rootdir: /local/data0/moved_data/publishablew/cleanlab/cleanlab
configfile: pyproject.toml
plugins: hypothesis-6.124.1
collecting ... collected 10 items

../../../../../../local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py::test_latent_py_ps_inv PASSED
../../../../../../local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py::test_latent_inv PASSED
../../../../../../local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py::test_latent_nm PASSED
../../../../../../local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py::test_latent_py PASSED
../../../../../../local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py::test_latent_py_warning PASSED
../../../../../../local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py::test_compute_py_err PASSED
../../../../../../local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py::test_compute_py_marginal_ps PASSED
../../../../../../local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py::test_pyx PASSED
../../../../../../local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py::test_pyx_error PASSED
../../../../../../local/data0/moved_data/publishablew/cleanlab/cleanlab/tests/test_latent_algebra.py::test_compute_py_method_marginal_true_labels_class_counts_none_error PASSED

============================== 10 passed in 0.61s ==============================
