output file:
processed_korniadepth_to_3d178.json
function:
depth_to_3d
Error Cases:

Pass or Failed: 0

Related Failed Test Cases:
{'FAILED ../../../../../../local/data0/moved_data/publishablew/kornia/kornia/tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-2]', '../../../../../../local/data0/moved_data/publishablew/kornia/kornia/tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-4] FAILED', '../../../../../../local/data0/moved_data/publishablew/kornia/kornia/tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-5] FAILED', 'FAILED ../../../../../../local/data0/moved_data/publishablew/kornia/kornia/tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-4]', 'FAILED ../../../../../../local/data0/moved_data/publishablew/kornia/kornia/tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-5]', '../../../../../../local/data0/moved_data/publishablew/kornia/kornia/tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-2] FAILED'}

All Test Cases On Generated code:
Setting up torch compile...
============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.3.3, pluggy-1.5.0 -- /local/data0/moved_data/publishablew/kornia/kornia/venv/bin/python
cachedir: .pytest_cache

cpu info:
	- Model name: AMD Ryzen 7 PRO 5845 8-Core Processor
	- Architecture: x86_64
	- CPU(s): 16
	- Thread(s) per core: 2
	- CPU max MHz: 4661.7178
	- CPU min MHz: 2200.0000
gpu info: {'GPU 0': 'NVIDIA GeForce RTX 3060'}
main deps:
    - kornia-0.7.4
    - torch-2.5.1+cu124
        - commit: a8d6afb511a69687bbb2b7e88a3cf67917e1697e
        - cuda: 12.4
        - nvidia-driver: 555.42.02
x deps:
    - accelerate-1.1.1
dev deps:
    - kornia_rs-0.1.7
    - onnx-1.17.0
gcc info: (Ubuntu 10.5.0-1ubuntu1~22.04) 10.5.0
available optimizers: {'', 'openxla', 'cudagraphs', 'inductor', 'onnxrt', 'tvm', 'jit', None}
model weights cached: []

rootdir: /local/data0/moved_data/publishablew/kornia/kornia
configfile: pyproject.toml
plugins: timeout-2.3.1, jaxtyping-0.2.38
collecting ... collected 4 items

../../../../../../local/data0/moved_data/publishablew/kornia/kornia/tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-1] FAILED
../../../../../../local/data0/moved_data/publishablew/kornia/kornia/tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-2] FAILED
../../../../../../local/data0/moved_data/publishablew/kornia/kornia/tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-4] FAILED
../../../../../../local/data0/moved_data/publishablew/kornia/kornia/tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-5] FAILED

=================================== FAILURES ===================================
______________ TestDepthTo3d.test_shapes_broadcast[cpu-float32-1] ______________

self = <tests.geometry.test_depth.TestDepthTo3d object at 0x708c7072ec20>
batch_size = 1, device = device(type='cpu'), dtype = torch.float32

    @pytest.mark.parametrize("batch_size", [1, 2, 4, 5])
    def test_shapes_broadcast(self, batch_size, device, dtype):
        depth = torch.rand(batch_size, 1, 3, 4, device=device, dtype=dtype)
        camera_matrix = torch.rand(1, 3, 3, device=device, dtype=dtype)
    
        points3d = kornia.geometry.depth.depth_to_3d(depth, camera_matrix)
>       assert points3d.shape == (batch_size, 3, 3, 4)
E       AttributeError: 'NoneType' object has no attribute 'shape'

/local/data0/moved_data/publishablew/kornia/kornia/tests/geometry/test_depth.py:31: AttributeError
______________ TestDepthTo3d.test_shapes_broadcast[cpu-float32-2] ______________

self = <tests.geometry.test_depth.TestDepthTo3d object at 0x708c7072eb60>
batch_size = 2, device = device(type='cpu'), dtype = torch.float32

    @pytest.mark.parametrize("batch_size", [1, 2, 4, 5])
    def test_shapes_broadcast(self, batch_size, device, dtype):
        depth = torch.rand(batch_size, 1, 3, 4, device=device, dtype=dtype)
        camera_matrix = torch.rand(1, 3, 3, device=device, dtype=dtype)
    
        points3d = kornia.geometry.depth.depth_to_3d(depth, camera_matrix)
>       assert points3d.shape == (batch_size, 3, 3, 4)
E       AttributeError: 'NoneType' object has no attribute 'shape'

/local/data0/moved_data/publishablew/kornia/kornia/tests/geometry/test_depth.py:31: AttributeError
______________ TestDepthTo3d.test_shapes_broadcast[cpu-float32-4] ______________

self = <tests.geometry.test_depth.TestDepthTo3d object at 0x708c7072eef0>
batch_size = 4, device = device(type='cpu'), dtype = torch.float32

    @pytest.mark.parametrize("batch_size", [1, 2, 4, 5])
    def test_shapes_broadcast(self, batch_size, device, dtype):
        depth = torch.rand(batch_size, 1, 3, 4, device=device, dtype=dtype)
        camera_matrix = torch.rand(1, 3, 3, device=device, dtype=dtype)
    
        points3d = kornia.geometry.depth.depth_to_3d(depth, camera_matrix)
>       assert points3d.shape == (batch_size, 3, 3, 4)
E       AttributeError: 'NoneType' object has no attribute 'shape'

/local/data0/moved_data/publishablew/kornia/kornia/tests/geometry/test_depth.py:31: AttributeError
______________ TestDepthTo3d.test_shapes_broadcast[cpu-float32-5] ______________

self = <tests.geometry.test_depth.TestDepthTo3d object at 0x708c7072efb0>
batch_size = 5, device = device(type='cpu'), dtype = torch.float32

    @pytest.mark.parametrize("batch_size", [1, 2, 4, 5])
    def test_shapes_broadcast(self, batch_size, device, dtype):
        depth = torch.rand(batch_size, 1, 3, 4, device=device, dtype=dtype)
        camera_matrix = torch.rand(1, 3, 3, device=device, dtype=dtype)
    
        points3d = kornia.geometry.depth.depth_to_3d(depth, camera_matrix)
>       assert points3d.shape == (batch_size, 3, 3, 4)
E       AttributeError: 'NoneType' object has no attribute 'shape'

/local/data0/moved_data/publishablew/kornia/kornia/tests/geometry/test_depth.py:31: AttributeError
=============================== warnings summary ===============================
tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-1]
tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-2]
tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-4]
tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-5]
  /local/data0/moved_data/publishablew/kornia/kornia/tests/geometry/test_depth.py:30: DeprecationWarning: Since kornia 0.8.0 the `depth_to_3d` is deprecated in favor of `depth_to_3d_v2`. This function will be replaced with the `depth_to_3d_v2` behaviour, where the that does not require the creation of a meshgrid. The return shape can be not backward compatible between these implementations.
    points3d = kornia.geometry.depth.depth_to_3d(depth, camera_matrix)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED ../../../../../../local/data0/moved_data/publishablew/kornia/kornia/tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-1]
FAILED ../../../../../../local/data0/moved_data/publishablew/kornia/kornia/tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-2]
FAILED ../../../../../../local/data0/moved_data/publishablew/kornia/kornia/tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-4]
FAILED ../../../../../../local/data0/moved_data/publishablew/kornia/kornia/tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-5]
======================== 4 failed, 4 warnings in 0.34s =========================


Final Test Result:
Setting up torch compile...
============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.3.3, pluggy-1.5.0 -- /local/data0/moved_data/publishablew/kornia/kornia/venv/bin/python
cachedir: .pytest_cache

cpu info:
	- Model name: AMD Ryzen 7 PRO 5845 8-Core Processor
	- Architecture: x86_64
	- CPU(s): 16
	- Thread(s) per core: 2
	- CPU max MHz: 4661.7178
	- CPU min MHz: 2200.0000
gpu info: {'GPU 0': 'NVIDIA GeForce RTX 3060'}
main deps:
    - kornia-0.7.4
    - torch-2.5.1+cu124
        - commit: a8d6afb511a69687bbb2b7e88a3cf67917e1697e
        - cuda: 12.4
        - nvidia-driver: 555.42.02
x deps:
    - accelerate-1.1.1
dev deps:
    - kornia_rs-0.1.7
    - onnx-1.17.0
gcc info: (Ubuntu 10.5.0-1ubuntu1~22.04) 10.5.0
available optimizers: {'', 'openxla', 'tvm', 'jit', 'cudagraphs', 'inductor', None, 'onnxrt'}
model weights cached: []

rootdir: /local/data0/moved_data/publishablew/kornia/kornia
configfile: pyproject.toml
plugins: timeout-2.3.1, jaxtyping-0.2.38
collecting ... collected 4 items

../../../../../../local/data0/moved_data/publishablew/kornia/kornia/tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-1] PASSED
../../../../../../local/data0/moved_data/publishablew/kornia/kornia/tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-2] PASSED
../../../../../../local/data0/moved_data/publishablew/kornia/kornia/tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-4] PASSED
../../../../../../local/data0/moved_data/publishablew/kornia/kornia/tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-5] PASSED

=============================== warnings summary ===============================
tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-1]
tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-2]
tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-4]
tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-5]
  /local/data0/moved_data/publishablew/kornia/kornia/tests/geometry/test_depth.py:30: DeprecationWarning: Since kornia 0.8.0 the `depth_to_3d` is deprecated in favor of `depth_to_3d_v2`. This function will be replaced with the `depth_to_3d_v2` behaviour, where the that does not require the creation of a meshgrid. The return shape can be not backward compatible between these implementations.
    points3d = kornia.geometry.depth.depth_to_3d(depth, camera_matrix)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================== 4 passed, 4 warnings in 0.16s =========================


Initial Result:
Setting up torch compile...
============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.3.3, pluggy-1.5.0 -- /local/data0/moved_data/publishablew/kornia/kornia/venv/bin/python
cachedir: .pytest_cache

cpu info:
	- Model name: AMD Ryzen 7 PRO 5845 8-Core Processor
	- Architecture: x86_64
	- CPU(s): 16
	- Thread(s) per core: 2
	- CPU max MHz: 4661.7178
	- CPU min MHz: 2200.0000
gpu info: {'GPU 0': 'NVIDIA GeForce RTX 3060'}
main deps:
    - kornia-0.7.4
    - torch-2.5.1+cu124
        - commit: a8d6afb511a69687bbb2b7e88a3cf67917e1697e
        - cuda: 12.4
        - nvidia-driver: 555.42.02
x deps:
    - accelerate-1.1.1
dev deps:
    - kornia_rs-0.1.7
    - onnx-1.17.0
gcc info: (Ubuntu 10.5.0-1ubuntu1~22.04) 10.5.0
available optimizers: {'', 'cudagraphs', 'inductor', 'tvm', 'onnxrt', 'jit', None, 'openxla'}
model weights cached: []

rootdir: /local/data0/moved_data/publishablew/kornia/kornia
configfile: pyproject.toml
plugins: timeout-2.3.1, jaxtyping-0.2.38
collecting ... collected 4 items

../../../../../../local/data0/moved_data/publishablew/kornia/kornia/tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-1] PASSED
../../../../../../local/data0/moved_data/publishablew/kornia/kornia/tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-2] PASSED
../../../../../../local/data0/moved_data/publishablew/kornia/kornia/tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-4] PASSED
../../../../../../local/data0/moved_data/publishablew/kornia/kornia/tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-5] PASSED

=============================== warnings summary ===============================
tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-1]
tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-2]
tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-4]
tests/geometry/test_depth.py::TestDepthTo3d::test_shapes_broadcast[cpu-float32-5]
  /local/data0/moved_data/publishablew/kornia/kornia/tests/geometry/test_depth.py:30: DeprecationWarning: Since kornia 0.8.0 the `depth_to_3d` is deprecated in favor of `depth_to_3d_v2`. This function will be replaced with the `depth_to_3d_v2` behaviour, where the that does not require the creation of a meshgrid. The return shape can be not backward compatible between these implementations.
    points3d = kornia.geometry.depth.depth_to_3d(depth, camera_matrix)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================== 4 passed, 4 warnings in 0.17s =========================
